### ISSUE TITLE
All resources are failured.

### ISSUE THREAD

**Issue by hiyangguo** [andornaut/vagrant-modern-ie#1]
```ruby
boxes = {
  "ie6"  => "http://aka.ms/ie6.xp.vagrant",
  "ie7"  => "http://aka.ms/ie7.vista.vagrant",
  "ie8"  => "http://aka.ms/ie8.win7.vagrant",
  "ie9"  => "http://aka.ms/ie9.win7.vagrant",
  "ie10" => "http://aka.ms/ie10.win8.vagrant",
  "ie11" => "http://aka.ms/ie11.win81.vagrant",
  "msedge" => "http://aka.ms/msedge.win10.vagrant",
}
```
These url now redirect to https://www.microsoft.com/en-us/?ref=aka

**Comment by andornaut** [comment]
If I find working vagrant box URLs, I'll update this project.

In the meantime (or as an alternative), you can use https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ to download a VM which includes both IE11 and Edge.

**Comment by hiyangguo** [comment]
Thank you very much . I made the box  from virtualbox . The first I init a VM , then [package box](https://www.vagrantup.com/docs/virtualbox/boxes.html#packaging-the-box) .
